common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 * @property integer $tickets_role
 * @property boolean $is_vip
 * @property integer $trainer_id
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_NEW = 0;
    const STATUS_ACTIVE = 1;
    const STATUS_DELETED = 2;

    const ROLE_SYSTEM = 0;
    const ROLE_ADMIN = 1;
    const ROLE_KURATOR = 2;
    const ROLE_USER = 3;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_NEW],
            ['status', 'in', 'range' => [self::STATUS_NEW, self::STATUS_ACTIVE, self::STATUS_DELETED]],

            ['role', 'default', 'value' => self::ROLE_USER],
            ['role', 'in', 'range' => [self::ROLE_ADMIN, self::ROLE_KURATOR, self::ROLE_USER]],

            ['phone', 'default', 'value' => ''],

            [['is_vip'], 'boolean'],

            [['fio'], 'string'],

            [['trainer_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['trainer_id' => 'id']],
            [['tickets_role'], 'exist', 'skipOnError' => true, 'targetClass' => UserRole::className(), 'targetAttribute' => ['is_trainer' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

      /**
     * Finds user by email
     *
     * @param string $username
     * @return static|null
     */
    public static function findByEmail($email, $status = self::STATUS_ACTIVE)
    {

        return static::findOne(['email' => $email, 'status' => $status]);

    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    public function generatePassword()
    {
    	return substr(Yii::$app->security->generateRandomString(), 0, 7);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrainer() {
        return $this->hasOne(User::className(), ['trainer_id' => 'id']);
    }

    /**
     * Set moor free trainer or set trainer by id
     * @param null $id
     */
    public function setTrainer($id = null) {
        if(is_null($id)) {
            $row = Yii::$app->db->createCommand("SELECT t.id,
(SELECT COUNT(*) FROM `user` WHERE trainer_id = t.id AND role = 2) AS c_run,
(SELECT COUNT(*) FROM `user` WHERE trainer_id = t.id AND role = 2) AS c_all
FROM user t WHERE role = 1
ORDER BY c_run, c_all")->queryOne();

            $this->trainer_id = $row['id'];
        }
        else {
            $this->trainer_id = $id;
        }
    }


    public function getAnket() {
        return $this->hasOne(UserAnket::className(), ['user_id' => 'id'])->one();
    }

    public function getFinanceAccount() {
    	return $this->hasOne(Finance_account::className(), ['user_id' => 'id'])->one();
    }

    public function getOrders() {
        return $this->hasMany(Order::className(), ['user_id' => 'id']);
    }

    public function getFinanceTransactions() {
    	return $this->hasMany(Finance_transaction::className(), ['user_id' => 'id']);
    }

    public function getGlobalFields() {
    	return $this->hasMany(User_global_field::className(), ['id_user' => 'id'])->all();
    }

}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\User;
use common\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\filters\AccessControl;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['*'],
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    // everything else is denied
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * @param \yii\base\Action $action
     * @return bool
     */
    public function beforeAction($action)
    {
        if(Yii::$app->user->identity->role == User::ROLE_KURATOR) {
            $this->layout = 'main_trainer';
        }

        return parent::beforeAction($action);
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if(Yii::$app->user->identity->role == User::ROLE_KURATOR) {
            return $this->render('index_trainer', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
        else {
            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionResend()
    {
        if(Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $response = array('status'=>'error', 'error'=>'');
            $user_id = Yii::$app->request->post('id');

            $user = User::findOne($user_id);
            if($user and $user->status == User::STATUS_ACTIVE) {
                $password = $user->generatePassword();
                $user->setPassword($password);
                $user->save();
                $mailer = Yii::$app->get('mail');
                $mailer->compose()
                    ->setTo($user->email)
                    ->setFrom([Yii::$app->params['adminEmail']=>Yii::$app->params['adminEmail']])
                    ->setSubject('Регистрация на проекте '.Yii::$app->params['siteData']['name'])
                    ->setHtmlBody($this->renderPartial('@frontend/views/mail/registration', ['promoCode'=>false, 'siteData'=>Yii::$app->params['siteData'], 'user'=>$user, 'pass'=>$password]))
                    ->send();
                $response['status'] = 'ok';
            } else {
                $response['error'] = 'Пользователь не найден';
            }
            return $response;
        }
    }

    public function actionAnket() {		$user_id = Yii::$app->request->get('user_id');

		$saved = '';
        $model = \common\models\UserAnket::find()->where(['user_id'=>$user_id])->one();
        if(is_array(Yii::$app->request->post()) and sizeof(Yii::$app->request->post()) > 0) {
        	//print_R(Yii::$app->request->post()); die();
	        if ($model->load(Yii::$app->request->post()) && $model->save()) {
	            $saved = 'Изменения успешно сохранены';
	        } else {
	        	$saved = 'Не удалось сохранить изменения';
	        }
        }

        $diet = \common\models\Diet::find()->where(['<', 'min', $model->kal])->andWhere(['>', 'max', $model->kal])->andWhere(['vegan'=>$model->vegan])->andWhere(['like', 'url', '%_'.$model->week.'_'.$model->day, false])->one();

  		return $this->render('anket', [
            'model' => $model,
            'saved' => $saved,
            'diet' => $diet
        ]);    }

    public function actionOrders() {
		$user_id = Yii::$app->request->get('user_id');

		$user = User::findOne($user_id);
        $orders = \common\models\Order::find()->where(['user_id'=>$user_id])->all();

  		return $this->render('orders', [
            'orders' => $orders,
            'user' => $user
        ]);
    }

    public function actionOrder() {
		$user_id = Yii::$app->request->get('user_id');
		$order_id = Yii::$app->request->get('order_id');

		$model = \common\models\Order::findOne($order_id);

		if(is_array(Yii::$app->request->post()) and sizeof(Yii::$app->request->post()) > 0) {			$start = Yii::$app->request->post('start');
			$start = strtotime($start);
			$model->datestart = $start;
			$model->save();
		}

  		return $this->render('order', [
            'model' => $model
        ]);
    }

    public function actionFreezeorder() {
    	if(Yii::$app->request->isAjax) {    		Yii::$app->response->format = Response::FORMAT_JSON;
    		$response = array('status'=>'error', 'error'=>'');
			$id = Yii::$app->request->post('id');
			$days = Yii::$app->request->post('days');

			$model = \common\models\Order::findOne($id);

			if($model->schedule_template == '') {				$model->datestart = $model->datestart + 86400 * $days;
				$model->expire = $model->expire + 86400 * $days;
				if($model->save()) {
					$response['status'] = 'ok';
				}			} elseif($model->active == 1) {				//$model->datestart = date('d.m.Y', $model->datestart + 86400 * $days);
				$model->expire = $model->expire + 86400 * $days;
				if($model->save()) {
					$response['status'] = 'ok';
				}

				//сюда внести чтобы трени перенеслись			}


	  		return $response;
        }
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use common\models\UserRole;
use common\models\User;

/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'fio')->label('ФИО')->textInput() ?>
    <?= $form->field($model, 'email')->label('Email')->textInput() ?>
    <?= $form->field($model, 'phone')->label('Номер телефона')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'role')->label('Роль')->dropDownList([
        User::ROLE_ADMIN => 'Администрация',
        User::ROLE_KURATOR => 'Куратор',
        User::ROLE_USER => 'Клиент',
    ]) ?>

    <?= $form->field($model, 'trainer_id')->label('Привязон к тренеру')->dropDownList(
        ArrayHelper::map(User::find()->where(['tickets_role' => '2'])->all(), 'id', 'fio'),
        [
        'prompt' => ''
    ]) ?>

    <?= $form->field($model, 'is_vip')->checkbox(['label' => 'VIP клиент']) ?>

    <?= $form->field($model, 'tickets_role')->label('Тикет-роль')->dropDownList(
        ArrayHelper::map(UserRole::find()->all(), 'id', 'name'),
        [
        'prompt' => ''
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton('Обновить', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/user/_search.php
<?php

use yii\helpers\Html;
use kartik\form\ActiveForm;
use yii\helpers\ArrayHelper;
use common\models\User;

/* @var $this yii\web\View */
/* @var $model common\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'type' => ActiveForm::TYPE_HORIZONTAL,
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <div class="row">
        <div class="col-lg-8">
            <?php /*echo $form->field($model, 'role')
                ->label('Роль')
                ->dropDownList([
                User::ROLE_ADMIN => 'Администратор',
                User::ROLE_KURATOR => 'Тренер',
                User::ROLE_USER => 'Клиент',
            ],
            [
                'prompt' => ''
            ]) */?>
            <?php echo $form->field($model, 'trainer_id')
                ->label('Тренер')
                ->dropDownList(ArrayHelper::map(User::find()->where(['tickets_role' => 2])->all(), 'id', 'fio'),[
                    'prompt' => ''
                ]) ?>
        </div>
        <div class="col-lg-2">
            <?php /*echo $form->field($model, 'is_trainer')->checkbox() */?>
            <?php echo $form->field($model, 'is_vip')->checkbox(['label' => 'VIP клиенты']) ?>
        </div>
        <div class="col-lg-2">
            <div class="form-group">
                <?= Html::submitButton('Поиск', ['class' => 'btn btn-primary']) ?>
            </div>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/user/anket.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$user = $model->getUser();

$this->title = 'Анкета: ' . $user->email;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => 'Анкета '.$user->email, 'url' => ['view', 'id' => $user->id]];

$model->gender = ($model->gender == 0) ?0:1;

?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>
    <div style="color: #f00"><?=$saved ?></div>

	<div class="user-form">

	    <?php $form = ActiveForm::begin(); ?>

	    <?= $form->field($model, 'fio')->label('ФИО')->textInput() ?>
	    <?= $form->field($model, 'born')->label('Дата рождения')->textInput() ?>
	    <?= $form->field($model, 'country')->label('Страна')->textInput() ?>
	    <?= $form->field($model, 'city')->label('Город')->textInput() ?>
	    <?= $form->field($model, 'insta')->label('Аккаунт в Instagram')->textInput() ?>
	    <?= $form->field($model, 'vk')->label('Аккаунт в ВК')->textInput() ?>
	    <?= $form->field($model, 'gender')->checkbox(['label' => 'Женщина']) ?>
	    <?= $form->field($model, 'growth')->label('Рост')->textInput() ?>
	    <?= $form->field($model, 'weight')->label('Вес')->textInput() ?>
	    <?= $form->field($model, 'breast_size')->label('Объём груди')->textInput() ?>
	    <?= $form->field($model, 'waist_size')->label('Обхват талии')->textInput() ?>
	    <?= $form->field($model, 'hip_size')->label('Обхват бёдер')->textInput() ?>
	    <?= $form->field($model, 'goal')->label('Цель')->dropDownList([
	        0 => 'Похудеть',
	        1 => 'Набрать вес',
	        2 => 'Рельеф',
	    ]) ?>
		<?= $form->field($model, 'vegan')->checkbox(['label' => 'Вегетарианец']) ?>
	    <?= $form->field($model, 'mother')->checkbox(['label' => 'Кормящая мать']) ?>
	    <?= $form->field($model, 'kal')->label('Калории')->textInput() ?>
	    <?= $form->field($model, 'day')->label('День')->dropDownList([
	        0, 1, 2, 3, 4, 5, 6, 7
	    ]) ?>
	    <?= $form->field($model, 'week')->label('Неделя')->dropDownList([
	        0, 1, 2, 3, 4
	    ]) ?>
	    <div><?=($diet)?$diet->title:'Нэт диет' ?></div>
	    <?= $form->field($model, 'status')->checkbox(['label' => 'Активна']) ?>

	    <div class="form-group">
	        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
	    </div>

	    <?php ActiveForm::end(); ?>

	</div>

</div>

backend/views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel common\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Пользователи';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php echo $this->render('_search', ['model' => $searchModel]); ?>

    <!--<p>
        <?/*= Html::a('Create User', ['create'], ['class' => 'btn btn-success']) */?>
    </p>-->
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            'fio',
            [
                'attribute' => 'email',
                'format' => 'html',
                'value' => function($data) {
                    return Html::a($data->email, \Yii::$app->urlManager->createAbsoluteUrl(["/user/update/$data->id"]));
                }
            ],
            'phone',
            // 'born',
            // 'growth',
            [
                'label' => 'Статус',
                'attribute' => 'status',
                'format' => 'raw',
                'value' => function($data) {
                    switch($data->status){
                        case (1):
                            return '<div class="btn btn-xs btn-primary">Активный</div>'.
                                (($data->is_vip) ? ' <div class="btn btn-xs btn-info">VIP</div>' : '')
                                .'<small><a href="#" class="send-reg-data pull-right" data-user-id="' . $data->id . '">Выслать рег данные</a></small>';
                            break;
                        case (0):
                            return '<div class="btn btn-xs btn-success">Новый</div>'.
                                (($data->is_vip) ? ' <div class="btn btn-xs btn-info">VIP</div>' : '')
                                .'<small>' . Html::a('Выслать рег данные', \Yii::$app->urlManager->createAbsoluteUrl(['/user/resend', 'id' => $data->id]), ['class' => 'text-xs pull-right']) . '</small>';
                        case (2):
                            return '<div class="btn btn-xs btn-danger">Удален</div>'.
                                (($data->is_vip) ? ' <div class="btn btn-xs btn-info">VIP</div>' : '');


                    }
                },
                'contentOptions' => ['class' => 'text-center'],
            ],
            /*[
                'label' => 'Дата регистрации',
                'attribute' => 'created_at',
                'filter' => \kartik\date\DatePicker::widget([
                    'model' => $searchModel,
                    'attribute' => 'creation_datetime',
                    'convertFormat' => true,
                    'removeButton' => false,
                    'pluginOptions' => [
                        'format' => 'yyyy-MM-dd',
                    ],
                ]),
            ],*/
            [
                'label' => 'Дата регистрации',
                'attribute' => 'created_at',
                'format' => 'html',
                'value' => function($data) {
                    return date('d.m.Y H:i:s', $data->created_at);
                }
            ],
            // 'updated_at',
            // 'role',
            // 'is_trainer',
            // 'trainer_id',
            [
                'label' => 'Действия',
                'format' => 'html',
                'value' => function($data){
                    return Html::a('Анкета', \Yii::$app->urlManager->createAbsoluteUrl(['/user/anket', 'user_id' => $data->id])).'&nbsp;'.Html::a('Заказы', \Yii::$app->urlManager->createAbsoluteUrl(['/user/orders', 'user_id' => $data->id])/*Html::a('Расписание', \Yii::$app->urlManager->createAbsoluteUrl(['/schedule', 'user_id' => $data->id])*/);
                }
            ],
            // ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>
<?php
$url = Url::toRoute(['resend']);
$script = <<< JS
    $(document).ready(function(){
		$('.send-reg-data').click(function(){
		    var user_id = $(this).data('user-id');
		    alert(user_id);
			$.ajax({
	            method: 'POST',
	            url: '$url',
	            data: { 'id': user_id },
	            dataType: 'json',
	            success: function(result) {
	                if(result && result.status && result.status == 'ok') {
                    	alert('Успешно отправлено');
	                } else {
                        alert('Не удалось отправить: ' + result.error);
	                }
	            },
	            error: function() {
                	alert('Не удалось отправить - ошибка сервера');
	            }
	        });

			return false;
		});
	});
JS;
$this->registerJs($script, yii\web\View::POS_READY);
?>

backend/views/user/index_trainer.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel common\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Клиенты';
$this->params['breadcrumbs'][] = $this->title;
?>
    <div class="user-index">

        <h1><?= Html::encode($this->title) ?></h1>
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

        <!--<p>
        <?/*= Html::a('Create User', ['create'], ['class' => 'btn btn-success']) */?>
    </p>-->
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                'id',
                'fio',
                'email:email',
                'phone',
                // 'born',
                // 'growth',
                /*[
                    'label' => 'Дата регистрации',
                    'attribute' => 'created_at',
                    'filter' => \kartik\date\DatePicker::widget([
                        'model' => $searchModel,
                        'attribute' => 'creation_datetime',
                        'convertFormat' => true,
                        'removeButton' => false,
                        'pluginOptions' => [
                            'format' => 'yyyy-MM-dd',
                        ],
                    ]),
                ],*/
                [
                    'label' => 'Дата регистрации',
                    'attribute' => 'created_at',
                    'format' => 'html',
                    'value' => function($data) {
                        return date('d.m.Y H:i:s', $data->created_at);
                    }
                ],
                // 'updated_at',
                // 'role',
                // 'is_trainer',
                // 'trainer_id',
                [
                    'label' => 'Действия',
                    'format' => 'html',
                    'value' => function($data){
                        return Html::a('Расписание', \Yii::$app->urlManager->createAbsoluteUrl(['/schedule', 'user_id' => $data->id]));
                    }
                ],
                // ['class' => 'yii\grid\ActionColumn'],
            ],
        ]); ?>
    </div>

backend/views/user/orders.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Заказы: ' . $user->email;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => 'Заказы '.$user->email, 'url' => ['orders', 'user_id' => $user->id]];

?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <table>
    <?php foreach($orders as $order): ?>
    	<tr><td><?=Html::a($order->getCourseGroup()->title, \Yii::$app->urlManager->createAbsoluteUrl(['/user/order', 'user_id' => $user->id, 'order_id' => $order->id])) ?></td></tr>
    <?php endforeach; ?>
    </table>

	<?/*<div class="user-form">

	    <?php $form = ActiveForm::begin(); ?>

	    <?= $form->field($model, 'fio')->label('ФИО')->textInput() ?>
	    <?= $form->field($model, 'born')->label('Дата рождения')->textInput() ?>
	    <?= $form->field($model, 'country')->label('Страна')->textInput() ?>
	    <?= $form->field($model, 'city')->label('Город')->textInput() ?>
	    <?= $form->field($model, 'insta')->label('Аккаунт в Instagram')->textInput() ?>
	    <?= $form->field($model, 'vk')->label('Аккаунт в ВК')->textInput() ?>
	    <?= $form->field($model, 'gender')->checkbox(['label' => 'Женщина']) ?>
	    <?= $form->field($model, 'growth')->label('Рост')->textInput() ?>
	    <?= $form->field($model, 'weight')->label('Вес')->textInput() ?>
	    <?= $form->field($model, 'breast_size')->label('Объём груди')->textInput() ?>
	    <?= $form->field($model, 'waist_size')->label('Обхват талии')->textInput() ?>
	    <?= $form->field($model, 'hip_size')->label('Обхват бёдер')->textInput() ?>
	    <?= $form->field($model, 'goal')->label('Цель')->dropDownList([
	        0 => 'Похудеть',
	        1 => 'Набрать вес',
	        2 => 'Рельеф',
	    ]) ?>
		<?= $form->field($model, 'vegan')->checkbox(['label' => 'Вегетарианец']) ?>
	    <?= $form->field($model, 'mother')->checkbox(['label' => 'Кормящая мать']) ?>
	    <?= $form->field($model, 'kal')->label('Калории')->textInput() ?>
	    <?= $form->field($model, 'day')->label('День')->dropDownList([
	        0, 1, 2, 3, 4, 5, 6, 7
	    ]) ?>
	    <?= $form->field($model, 'week')->label('Неделя')->dropDownList([
	        0, 1, 2, 3, 4
	    ]) ?>
	    <div><?=$diet->title ?></div>
	    <?= $form->field($model, 'status')->checkbox(['label' => 'Активна']) ?>

	    <div class="form-group">
	        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
	    </div>

	    <?php ActiveForm::end(); ?>

	</div>*/?>

</div>

backend/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Пользователь: ' . $model->email;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->email, 'url' => ['view', 'id' => $model->id]];
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>