common/models/Webinar.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%webinar}}".
 *
 * @property string $id
 * @property string $title
 * @property string $preview
 * @property string $short_text
 * @property string $full_text
 * @property string $video_content
 * @property string $date
 */
class Webinar extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%webinar}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'short_text', 'date'], 'required'],
            [['short_text', 'full_text', 'video_content'], 'string'],
            [['date'], 'safe'],
            [['title', 'preview'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Название вебинара',
            'preview' => 'Изображение',
            'short_text' => 'Короткий текст вебинара',
            'full_text' => 'Подробный текст вебинара',
            'video_content' => 'Видео контент',
            'date' => 'Дата',
        ];
    }
}

backend/controllers/WebinarController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Webinar;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;

class WebinarController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['*'],
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    // everything else is denied
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Webinar models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Webinar::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Webinar model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Webinar();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();

            $previewFile = UploadedFile::getInstance($model, 'preview');
            if (!is_null($previewFile)) {
                $previewFile->saveAs(Yii::getAlias('@frontend/web/public/webinar_' . $model->id . '.' . $previewFile->extension));
                $model->preview = '/public/webinar_' . $model->id . '.' . $previewFile->extension;
            }
            $model->save();

            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Webinar model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();

            $previewFile = UploadedFile::getInstance($model, 'preview');
            if (!is_null($previewFile)) {
                $previewFile->saveAs(Yii::getAlias('@frontend/web/public/webinar_' . $model->id . '.' . $previewFile->extension));
                $model->preview = '/public/webinar_' . $model->id . '.' . $previewFile->extension;
            }
            $model->save();
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Webinar model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Webinar model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Webinar the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Webinar::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/WebinarsController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Webinar;
use yii\data\ActiveDataProvider;
use yii\data\Pagination;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

class WebinarsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['*'],
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    // everything else is denied
                ],
            ],
        ];
    }

    /**
     * Lists all Webinar models.
     * @return mixed
     */
    public function actionIndex()
    {
        $query = Webinar::find();
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $models = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();


        return $this->render('index', [
            'models' => $models,
            'pages' => $pages,
        ]);
    }


    public function actionView($id)
    {
        $model = Webinar::findOne(['id' => $id]);
        if(is_null($model)) {
            throw new NotFoundHttpException();
        }

        return $this->render('webinar', [
            'model' => $model
        ]);
    }
}

backend/views/webinar/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use zxbodya\yii2\tinymce\TinyMce;
use zxbodya\yii2\elfinder\TinyMceElFinder;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model common\models\Webinar */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="webinar-form">

    <?php $form = ActiveForm::begin([
        'options' => [
            'enctype' => 'multipart/form-data',
        ]
    ]); ?>

    <div class="row">
        <div class="col-lg-8">

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'short_text')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'full_text')->widget(TinyMce::className(), [
        'fileManager' => [
            'class' => TinyMceElFinder::className(),
            'connectorRoute' => 'elfinder/connector',
        ],
        'language' => 'ru'
    ]) ?>

    <?= $form->field($model, 'video_content')->widget(TinyMce::className(), [
        'settings'=> [
            'menubar' => false,
            'toolbar' => 'media code preview',
            'plugins' => ['media', 'code', 'preview'],
            'toolbar_items_size' => 'large'
        ],
        'fileManager' => [
            'class' => TinyMceElFinder::className(),
            'connectorRoute' => 'elfinder/connector',
        ],
        'language' => 'ru',
    ]); ?>

        </div>
        <div class="col-lg-4">
            <?= $form->field($model, 'date')->widget(DatePicker::className(), [
                'type' => DatePicker::TYPE_COMPONENT_PREPEND,
                'value' => $model->isNewRecord ? date("Y-m-d") : $model->date,
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'yyyy-mm-dd'
                ]
            ]); ?>

            <?= $form->field($model, 'preview')->fileInput() ?>

            <?php if(!empty($model->preview)): ?>
                <p><img src="<?= $model->preview ?>" class="img-thumbnail img-responsive"></p>
            <?php endif; ?>
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/webinar/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Webinar */

$this->title = 'Создать вебинар';
$this->params['breadcrumbs'][] = ['label' => 'Вебинары', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="webinar-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/webinar/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Вебинары';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="webinar-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Создать вебинар', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [

            'id',
            [
                'attribute' => 'title',
                'format' => 'html',
                'value' => function($data){
                    return Html::a($data->title, \Yii::$app->urlManager->createAbsoluteUrl(['webinar/update', 'id' => $data->id]));
                }
            ],
            [
                'format' => 'raw',
                'value' => function($data) {
                    return Html::a('<span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>', ['delete', 'id' => $data->id], [
                        'class' => 'text-danger',
                        'data' => [
                            'confirm' => 'Вы уверены, что хотите удалить этот вебинар?',
                            'method' => 'post',
                        ]
                    ]);
                },
                'contentOptions' => ['class' => 'text-center'],
            ],
        ],
    ]); ?>
</div>

backend/views/webinar/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Webinar */

$this->title = 'Обновить вебинар: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Вебинары', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="webinar-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>